
PLAYSET_TYPES = [
    { id: "1", playset_type: "Convivencia Escolar", image_url: "https://i.imgur.com/q6oPqTX.jpg", description: "Es nuestra Ludoteca mas utilizada en las escuelas  durante el 2019,  los juegos  van desde los mas pequeños con propuestas colaborativas para no lectores hasta juegos y oportunidades en Docentes y Apoderados por que también son parte de la convivencia escolar, la propuesta se encuentra alineada a la política nacional de convivencia escolar buscando fortalecer el trato respetuoso, la comunicación, la resolución pacífica de los conflictos y equipar las oportunidades de juegos para niñas como una estrategia de equidad de género " },
    { id: "2", playset_type: "Formación Ciudadana", image_url: "https://i.imgur.com/YE8UCqD.jpg", description: "Los Juegos de la Ludoteca de Formación Ciudadana se encuentran seleccionados para el trabajo desde el segundo ciclo básico,  combinando contenidos específicos de cara a la ciudadanía hasta las destrezas y habilidades sociales para ejercerla , se refuerzan en sus títulos elementos como la comunicación, la toma de decisiones responsables, fomentar la valoración de la diversidad social y cultural del país, el respeto por los derechos humanos y la participación de los estudiantes en temas de interés público, entre otras materias.." },
    { id: "3", playset_type: "Decreto 83, DUA", image_url: "https://i.imgur.com/KuWUQJm.jpg", description: "La inclusión y la disminución de la segregación escolar son una de las tareas con mayor impacto cultural en el largo plazo , entregar espacios de trabajo diversos que contengan en todo momento elementos socioemocionales son claves ya que la diversidad siempre tiene que ver con la interacción y coordinación con otros, es entonces que el uso del Juego logra  ser de impacto en un sano proceso social e individual , propiciando la colaboración , la participación de todos y todas entregando además una herramienta de apoyo real a los docentes de aula, ya que el juego por su diseño no solamente acoge a quienes tienes dificultades a la hora de avanzar si no que también motiva y mantiene motivados a aquellos que aprenden rápidamente, integrando a este grupo al trabajo permanente. La selección fortalece habilidades de Lectura y Pensamiento matemático desde primero a sexto básico." },
    { id: "4", playset_type: "PIE", image_url: "https://i.imgur.com/HxgsqLd.jpg", description: "Selección de uso específico para el desarrollo de habilidades, destrezas y auto concepto positivo , el objetivo principal de la Ludoteca Escolar PIE es ser un apoyo permanente en el desarrollo Socioemocional de niños y niñas que presentan NEE , los juegos abordan las necesidades del primer ciclo básico, con  elementos que buscan fortalecer la concentración, participación , motivación  y apropiación segura de los elementos básicos del desarrollo escolar." },
    { id: "5", playset_type: "Estrategias de Transición (373)", image_url: "https://i.imgur.com/mvLMRhD.jpg", description: "Entre los elementos que dispone el Decreto de transición, se destaca la  creación y  apoyo de instancias para validar el juego y las situaciones lúdicas como la forma natural de aprender en los niños y niñas pequeños/as, por lo tanto la estrategia a implementar debe proponer explícitamente iniciativas para la articulación entre ambos niveles educativos, que propicien experiencias para el aprendizaje y juego que enriquezcan sus posibilidades de comprensión de sí mismos y del mundo, en diversos espacios del establecimiento, y también si es posible, fuera de este. La selección de esta Ludoteca  considera títulos desde no lectores y se encuentra pensada para espacios de Aula, entregando la oportunidad de acceder libremente a ellos por parte de los estudiantes apoyando además actividades guiadas por el docente." },
    { id: "6", playset_type: "Equipo directivo", image_url: "https://i.imgur.com/PNHMbjE.jpg", description: "" },
    { id: "7", playset_type: "Taller PlayGo", image_url: "https://i.imgur.com/Uv0opz1.jpg", description: "" },
    { id: "8", playset_type: "Espacios CRA", image_url: "https://i.imgur.com/c0Xw251.jpg", description: "" },
    { id: "9", playset_type: "Vuelve a clases, vuelve a jugar", image_url: "https://i.imgur.com/TTHcVCI.jpg", description: "" }
  ]
