# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

# Regiones
rm = Region.find_or_create_by(name: "Región Metropolitana de Santiago", short_name: 'RM')
r1 = Region.find_or_create_by(name: "Región de Arica y Parinacota", short_name: 'I')
r2 = Region.find_or_create_by(name: "Región de Tarapacá", short_name: 'II')
r3 = Region.find_or_create_by(name: "Región de Antofagasta", short_name: 'III')
r4 = Region.find_or_create_by(name: "Región de Atacama", short_name: 'IV')
r5 = Region.find_or_create_by(name: "Región de Coquimbo", short_name: 'V')
r6 = Region.find_or_create_by(name: "Región de Valparaiso", short_name: 'VI')
r7 = Region.find_or_create_by(name: "Región del Libertador General Bernardo O'Higgins", short_name: 'RM')
r8 = Region.find_or_create_by(name: "Región del Maule", short_name: 'VII')
r9 = Region.find_or_create_by(name: "Región del Biobío", short_name: 'VIII')
r10 = Region.find_or_create_by(name: "Región de la Araucanía", short_name: 'IX')
r11 = Region.find_or_create_by(name: "Región de los Ríos", short_name: 'XIV')
r12 = Region.find_or_create_by(name: "Región de los Lagos", short_name: 'X')
r13 = Region.find_or_create_by(name: "Región de Aysén del General Carlos Ibáñez del Campo", short_name: 'XI')
r14 = Region.find_or_create_by(name: "Región de Magallanes y de la Antártica Chilena", short_name: 'XII')

# Comunas
Commune.find_or_create_by(region: rm, name: "Colina")
Commune.find_or_create_by(region: rm, name: "Lampa")
Commune.find_or_create_by(region: rm, name: "Tiltil")
Commune.find_or_create_by(region: rm, name: "Pirque")
Commune.find_or_create_by(region: rm, name: "Puente Alto")
Commune.find_or_create_by(region: rm, name: "San José de Maipo")
Commune.find_or_create_by(region: rm, name: "Buin")
Commune.find_or_create_by(region: rm, name: "Calera de Tango")
Commune.find_or_create_by(region: rm, name: "Paine")
Commune.find_or_create_by(region: rm, name: "San Bernardo")
Commune.find_or_create_by(region: rm, name: "Alhué")
Commune.find_or_create_by(region: rm, name: "Curacaví")
Commune.find_or_create_by(region: rm, name: "María Pinto")
Commune.find_or_create_by(region: rm, name: "Melipilla")
Commune.find_or_create_by(region: rm, name: "San Pedro")
Commune.find_or_create_by(region: rm, name: "Cerrillos")
Commune.find_or_create_by(region: rm, name: "Cerro Navia")
Commune.find_or_create_by(region: rm, name: "Conchalí")
Commune.find_or_create_by(region: rm, name: "El Bosque")
Commune.find_or_create_by(region: rm, name: "Estación Central")
Commune.find_or_create_by(region: rm, name: "Huechuraba")
Commune.find_or_create_by(region: rm, name: "Independencia")
Commune.find_or_create_by(region: rm, name: "La Cisterna")
Commune.find_or_create_by(region: rm, name: "La Granja")
Commune.find_or_create_by(region: rm, name: "La Florida")
Commune.find_or_create_by(region: rm, name: "La Pintana")
Commune.find_or_create_by(region: rm, name: "La Reina")
Commune.find_or_create_by(region: rm, name: "Las Condes")
Commune.find_or_create_by(region: rm, name: "Lo Barnechea")
Commune.find_or_create_by(region: rm, name: "Lo Espejo")
Commune.find_or_create_by(region: rm, name: "Lo Prado")
Commune.find_or_create_by(region: rm, name: "Macul")
Commune.find_or_create_by(region: rm, name: "Maipú")
Commune.find_or_create_by(region: rm, name: "Ñuñoa")
Commune.find_or_create_by(region: rm, name: "Pedro Aguirre Cerda")
Commune.find_or_create_by(region: rm, name: "Peñalolén")
Commune.find_or_create_by(region: rm, name: "Providencia")
Commune.find_or_create_by(region: rm, name: "Pudahuel")
Commune.find_or_create_by(region: rm, name: "Quilicura")
Commune.find_or_create_by(region: rm, name: "Quinta Normal")
Commune.find_or_create_by(region: rm, name: "Recoleta")
Commune.find_or_create_by(region: rm, name: "Renca")
Commune.find_or_create_by(region: rm, name: "San Miguel")
Commune.find_or_create_by(region: rm, name: "San Joaquín")
Commune.find_or_create_by(region: rm, name: "San Ramón")
Commune.find_or_create_by(region: rm, name: "Santiago")
Commune.find_or_create_by(region: rm, name: "Vitacura")
Commune.find_or_create_by(region: rm, name: "El Monte")
Commune.find_or_create_by(region: rm, name: "Isla de Maipo")
Commune.find_or_create_by(region: rm, name: "Padre Hurtado")
Commune.find_or_create_by(region: rm, name: "Peñaflor")
Commune.find_or_create_by(region: rm, name: "Talagante")
Commune.find_or_create_by(region: r1, name: "Arica")
Commune.find_or_create_by(region: r1, name: "Camarones")
Commune.find_or_create_by(region: r1, name: "Putre")
Commune.find_or_create_by(region: r1, name: "General Lagos")
Commune.find_or_create_by(region: r2, name: "Iquique")
Commune.find_or_create_by(region: r2, name: "Alto Hospicio")
Commune.find_or_create_by(region: r2, name: "Pozo Almonte")
Commune.find_or_create_by(region: r2, name: "Camiña")
Commune.find_or_create_by(region: r2, name: "Colchane")
Commune.find_or_create_by(region: r2, name: "Huara")
Commune.find_or_create_by(region: r2, name: "Pica")
Commune.find_or_create_by(region: r3, name: "Antofagasta")
Commune.find_or_create_by(region: r3, name: "Mejillones")
Commune.find_or_create_by(region: r3, name: "Sierra Gorda")
Commune.find_or_create_by(region: r3, name: "Taltal")
Commune.find_or_create_by(region: r3, name: "Calama")
Commune.find_or_create_by(region: r3, name: "Ollagüe")
Commune.find_or_create_by(region: r3, name: "San Pedro de Atacama")
Commune.find_or_create_by(region: r3, name: "Tocopilla")
Commune.find_or_create_by(region: r3, name: "María Elena")
Commune.find_or_create_by(region: r4, name: "Copiapó")
Commune.find_or_create_by(region: r4, name: "Caldera")
Commune.find_or_create_by(region: r4, name: "Tierra Amarilla")
Commune.find_or_create_by(region: r4, name: "Chañaral")
Commune.find_or_create_by(region: r4, name: "Diego de Almagro")
Commune.find_or_create_by(region: r4, name: "Vallenar")
Commune.find_or_create_by(region: r4, name: "Alto del Carmen")
Commune.find_or_create_by(region: r4, name: "Freirina")
Commune.find_or_create_by(region: r4, name: "Huasco")
Commune.find_or_create_by(region: r5, name: "La Serena")
Commune.find_or_create_by(region: r5, name: "Coquimbo")
Commune.find_or_create_by(region: r5, name: "Andacollo")
Commune.find_or_create_by(region: r5, name: "La Higuera")
Commune.find_or_create_by(region: r5, name: "Paiguano")
Commune.find_or_create_by(region: r5, name: "Vicuña")
Commune.find_or_create_by(region: r5, name: "Illapel")
Commune.find_or_create_by(region: r5, name: "Canela")
Commune.find_or_create_by(region: r5, name: "Los Vilos")
Commune.find_or_create_by(region: r5, name: "Salamanca")
Commune.find_or_create_by(region: r5, name: "Ovalle")
Commune.find_or_create_by(region: r5, name: "Combarbalá")
Commune.find_or_create_by(region: r5, name: "Monte Patria")
Commune.find_or_create_by(region: r5, name: "Punitaqui")
Commune.find_or_create_by(region: r5, name: "Río Hurtado")
Commune.find_or_create_by(region: r6, name: "Valparaíso")
Commune.find_or_create_by(region: r6, name: "Casablanca")
Commune.find_or_create_by(region: r6, name: "Concón")
Commune.find_or_create_by(region: r6, name: "Juan Fernández")
Commune.find_or_create_by(region: r6, name: "Puchuncaví")
Commune.find_or_create_by(region: r6, name: "Quintero")
Commune.find_or_create_by(region: r6, name: "Viña del Mar")
Commune.find_or_create_by(region: r6, name: "Isla de Pascua")
Commune.find_or_create_by(region: r6, name: "Los Andes")
Commune.find_or_create_by(region: r6, name: "Calle Larga")
Commune.find_or_create_by(region: r6, name: "Rinconada")
Commune.find_or_create_by(region: r6, name: "San Esteban")
Commune.find_or_create_by(region: r6, name: "La Ligua")
Commune.find_or_create_by(region: r6, name: "Cabildo")
Commune.find_or_create_by(region: r6, name: "Papudo")
Commune.find_or_create_by(region: r6, name: "Petorca")
Commune.find_or_create_by(region: r6, name: "Zapallar")
Commune.find_or_create_by(region: r6, name: "Quillota")
Commune.find_or_create_by(region: r6, name: "Calera")
Commune.find_or_create_by(region: r6, name: "Hijuelas")
Commune.find_or_create_by(region: r6, name: "La Cruz")
Commune.find_or_create_by(region: r6, name: "Nogales")
Commune.find_or_create_by(region: r6, name: "San Antonio")
Commune.find_or_create_by(region: r6, name: "Algarrobo")
Commune.find_or_create_by(region: r6, name: "Cartagena")
Commune.find_or_create_by(region: r6, name: "El Quisco")
Commune.find_or_create_by(region: r6, name: "El Tabo")
Commune.find_or_create_by(region: r6, name: "Santo Domingo")
Commune.find_or_create_by(region: r6, name: "San Felipe")
Commune.find_or_create_by(region: r6, name: "Catemu")
Commune.find_or_create_by(region: r6, name: "Llaillay")
Commune.find_or_create_by(region: r6, name: "Panquehue")
Commune.find_or_create_by(region: r6, name: "Putaendo")
Commune.find_or_create_by(region: r6, name: "Santa María")
Commune.find_or_create_by(region: r6, name: "Quilpué")
Commune.find_or_create_by(region: r6, name: "Limache")
Commune.find_or_create_by(region: r6, name: "Olmué")
Commune.find_or_create_by(region: r6, name: "Villa Alemana")
Commune.find_or_create_by(region: r7, name: "Rancagua")
Commune.find_or_create_by(region: r7, name: "Codegua")
Commune.find_or_create_by(region: r7, name: "Coinco")
Commune.find_or_create_by(region: r7, name: "Coltauco")
Commune.find_or_create_by(region: r7, name: "Doñihue")
Commune.find_or_create_by(region: r7, name: "Graneros")
Commune.find_or_create_by(region: r7, name: "Las Cabras")
Commune.find_or_create_by(region: r7, name: "Machalí")
Commune.find_or_create_by(region: r7, name: "Malloa")
Commune.find_or_create_by(region: r7, name: "Mostazal")
Commune.find_or_create_by(region: r7, name: "Olivar")
Commune.find_or_create_by(region: r7, name: "Peumo")
Commune.find_or_create_by(region: r7, name: "Pichidegua")
Commune.find_or_create_by(region: r7, name: "Quinta de Tilcoco")
Commune.find_or_create_by(region: r7, name: "Rengo")
Commune.find_or_create_by(region: r7, name: "Requínoa")
Commune.find_or_create_by(region: r7, name: "San Vicente")
Commune.find_or_create_by(region: r7, name: "Pichilemu")
Commune.find_or_create_by(region: r7, name: "La Estrella")
Commune.find_or_create_by(region: r7, name: "Litueche")
Commune.find_or_create_by(region: r7, name: "Marchihue")
Commune.find_or_create_by(region: r7, name: "Navidad")
Commune.find_or_create_by(region: r7, name: "Paredones")
Commune.find_or_create_by(region: r7, name: "San Fernando")
Commune.find_or_create_by(region: r7, name: "Chépica")
Commune.find_or_create_by(region: r7, name: "Chimbarongo")
Commune.find_or_create_by(region: r7, name: "Lolol")
Commune.find_or_create_by(region: r7, name: "Nancagua")
Commune.find_or_create_by(region: r7, name: "Palmilla")
Commune.find_or_create_by(region: r7, name: "Peralillo")
Commune.find_or_create_by(region: r7, name: "Placilla")
Commune.find_or_create_by(region: r7, name: "Pumanque")
Commune.find_or_create_by(region: r7, name: "Santa Cruz")
Commune.find_or_create_by(region: r8, name: "Talca")
Commune.find_or_create_by(region: r8, name: "Constitución")
Commune.find_or_create_by(region: r8, name: "Curepto")
Commune.find_or_create_by(region: r8, name: "Empedrado")
Commune.find_or_create_by(region: r8, name: "Maule")
Commune.find_or_create_by(region: r8, name: "Pelarco")
Commune.find_or_create_by(region: r8, name: "Pencahue")
Commune.find_or_create_by(region: r8, name: "Río Claro")
Commune.find_or_create_by(region: r8, name: "San Clemente")
Commune.find_or_create_by(region: r8, name: "San Rafael")
Commune.find_or_create_by(region: r8, name: "Cauquenes")
Commune.find_or_create_by(region: r8, name: "Chanco")
Commune.find_or_create_by(region: r8, name: "Pelluhue")
Commune.find_or_create_by(region: r8, name: "Curicó")
Commune.find_or_create_by(region: r8, name: "Hualañé")
Commune.find_or_create_by(region: r8, name: "Licantén")
Commune.find_or_create_by(region: r8, name: "Molina")
Commune.find_or_create_by(region: r8, name: "Rauco")
Commune.find_or_create_by(region: r8, name: "Romeral")
Commune.find_or_create_by(region: r8, name: "Sagrada Familia")
Commune.find_or_create_by(region: r8, name: "Teno")
Commune.find_or_create_by(region: r8, name: "Vichuquén")
Commune.find_or_create_by(region: r8, name: "Linares")
Commune.find_or_create_by(region: r8, name: "Colbún")
Commune.find_or_create_by(region: r8, name: "Longaví")
Commune.find_or_create_by(region: r8, name: "Parral")
Commune.find_or_create_by(region: r8, name: "Retiro")
Commune.find_or_create_by(region: r8, name: "San Javier")
Commune.find_or_create_by(region: r8, name: "Villa Alegre")
Commune.find_or_create_by(region: r8, name: "Yerbas Buenas")
Commune.find_or_create_by(region: r9, name: "Concepción")
Commune.find_or_create_by(region: r9, name: "Coronel")
Commune.find_or_create_by(region: r9, name: "Chiguayante")
Commune.find_or_create_by(region: r9, name: "Florida")
Commune.find_or_create_by(region: r9, name: "Hualqui")
Commune.find_or_create_by(region: r9, name: "Lota")
Commune.find_or_create_by(region: r9, name: "Penco")
Commune.find_or_create_by(region: r9, name: "San Pedro de La Paz")
Commune.find_or_create_by(region: r9, name: "Santa Juana")
Commune.find_or_create_by(region: r9, name: "Talcahuano")
Commune.find_or_create_by(region: r9, name: "Tomé")
Commune.find_or_create_by(region: r9, name: "Hualpén")
Commune.find_or_create_by(region: r9, name: "Lebu")
Commune.find_or_create_by(region: r9, name: "Arauco")
Commune.find_or_create_by(region: r9, name: "Cañete")
Commune.find_or_create_by(region: r9, name: "Contulmo")
Commune.find_or_create_by(region: r9, name: "Curanilahue")
Commune.find_or_create_by(region: r9, name: "Los Álamos")
Commune.find_or_create_by(region: r9, name: "Tirúa")
Commune.find_or_create_by(region: r9, name: "Los Ángeles")
Commune.find_or_create_by(region: r9, name: "Antuco")
Commune.find_or_create_by(region: r9, name: "Cabrero")
Commune.find_or_create_by(region: r9, name: "Laja")
Commune.find_or_create_by(region: r9, name: "Mulchén")
Commune.find_or_create_by(region: r9, name: "Nacimiento")
Commune.find_or_create_by(region: r9, name: "Negrete")
Commune.find_or_create_by(region: r9, name: "Quilaco")
Commune.find_or_create_by(region: r9, name: "Quilleco")
Commune.find_or_create_by(region: r9, name: "San Rosendo")
Commune.find_or_create_by(region: r9, name: "Santa Bárbara")
Commune.find_or_create_by(region: r9, name: "Tucapel")
Commune.find_or_create_by(region: r9, name: "Yumbel")
Commune.find_or_create_by(region: r9, name: "Alto Biobío")
Commune.find_or_create_by(region: r9, name: "Chillán")
Commune.find_or_create_by(region: r9, name: "Bulnes")
Commune.find_or_create_by(region: r9, name: "Cobquecura")
Commune.find_or_create_by(region: r9, name: "Coelemu")
Commune.find_or_create_by(region: r9, name: "Coihueco")
Commune.find_or_create_by(region: r9, name: "Chillán Viejo")
Commune.find_or_create_by(region: r9, name: "El Carmen")
Commune.find_or_create_by(region: r9, name: "Ninhue")
Commune.find_or_create_by(region: r9, name: "Ñiquén")
Commune.find_or_create_by(region: r9, name: "Pemuco")
Commune.find_or_create_by(region: r9, name: "Pinto")
Commune.find_or_create_by(region: r9, name: "Portezuelo")
Commune.find_or_create_by(region: r9, name: "Quillón")
Commune.find_or_create_by(region: r9, name: "Quirihue")
Commune.find_or_create_by(region: r9, name: "Ránquil")
Commune.find_or_create_by(region: r9, name: "San Carlos")
Commune.find_or_create_by(region: r9, name: "San Fabián")
Commune.find_or_create_by(region: r9, name: "San Ignacio")
Commune.find_or_create_by(region: r9, name: "San Nicolás")
Commune.find_or_create_by(region: r9, name: "Treguaco")
Commune.find_or_create_by(region: r9, name: "Yungay")
Commune.find_or_create_by(region: r10, name: "Temuco")
Commune.find_or_create_by(region: r10, name: "Carahue")
Commune.find_or_create_by(region: r10, name: "Cunco")
Commune.find_or_create_by(region: r10, name: "Curarrehue")
Commune.find_or_create_by(region: r10, name: "Freire")
Commune.find_or_create_by(region: r10, name: "Galvarino")
Commune.find_or_create_by(region: r10, name: "Gorbea")
Commune.find_or_create_by(region: r10, name: "Lautaro")
Commune.find_or_create_by(region: r10, name: "Loncoche")
Commune.find_or_create_by(region: r10, name: "Melipeuco")
Commune.find_or_create_by(region: r10, name: "Nueva Imperial")
Commune.find_or_create_by(region: r10, name: "Padre Las Casas")
Commune.find_or_create_by(region: r10, name: "Perquenco")
Commune.find_or_create_by(region: r10, name: "Pitrufquén")
Commune.find_or_create_by(region: r10, name: "Pucón")
Commune.find_or_create_by(region: r10, name: "Saavedra")
Commune.find_or_create_by(region: r10, name: "Teodoro Schmidt")
Commune.find_or_create_by(region: r10, name: "Toltén")
Commune.find_or_create_by(region: r10, name: "Vilcún")
Commune.find_or_create_by(region: r10, name: "Villarrica")
Commune.find_or_create_by(region: r10, name: "Cholchol")
Commune.find_or_create_by(region: r10, name: "Angol")
Commune.find_or_create_by(region: r10, name: "Collipulli")
Commune.find_or_create_by(region: r10, name: "Curacautín")
Commune.find_or_create_by(region: r10, name: "Ercilla")
Commune.find_or_create_by(region: r10, name: "Lonquimay")
Commune.find_or_create_by(region: r10, name: "Los Sauces")
Commune.find_or_create_by(region: r10, name: "Lumaco")
Commune.find_or_create_by(region: r10, name: "Purén")
Commune.find_or_create_by(region: r10, name: "Renaico")
Commune.find_or_create_by(region: r10, name: "Traiguén")
Commune.find_or_create_by(region: r10, name: "Victoria")
Commune.find_or_create_by(region: r11, name: "Valdivia")
Commune.find_or_create_by(region: r11, name: "Corral")
Commune.find_or_create_by(region: r11, name: "Lanco")
Commune.find_or_create_by(region: r11, name: "Los Lagos")
Commune.find_or_create_by(region: r11, name: "Máfil")
Commune.find_or_create_by(region: r11, name: "Mariquina")
Commune.find_or_create_by(region: r11, name: "Paillaco")
Commune.find_or_create_by(region: r11, name: "Panguipulli")
Commune.find_or_create_by(region: r11, name: "La Unión")
Commune.find_or_create_by(region: r11, name: "Futrono")
Commune.find_or_create_by(region: r11, name: "Lago Ranco")
Commune.find_or_create_by(region: r11, name: "Río Bueno")
Commune.find_or_create_by(region: r12, name: "Puerto Montt")
Commune.find_or_create_by(region: r12, name: "Calbuco")
Commune.find_or_create_by(region: r12, name: "Cochamó")
Commune.find_or_create_by(region: r12, name: "Fresia")
Commune.find_or_create_by(region: r12, name: "Frutillar")
Commune.find_or_create_by(region: r12, name: "Los Muermos")
Commune.find_or_create_by(region: r12, name: "Llanquihue")
Commune.find_or_create_by(region: r12, name: "Maullín")
Commune.find_or_create_by(region: r12, name: "Puerto Varas")
Commune.find_or_create_by(region: r12, name: "Castro")
Commune.find_or_create_by(region: r12, name: "Ancud")
Commune.find_or_create_by(region: r12, name: "Chonchi")
Commune.find_or_create_by(region: r12, name: "Curaco de Vélez")
Commune.find_or_create_by(region: r12, name: "Dalcahue")
Commune.find_or_create_by(region: r12, name: "Puqueldón")
Commune.find_or_create_by(region: r12, name: "Queilén")
Commune.find_or_create_by(region: r12, name: "Quellón")
Commune.find_or_create_by(region: r12, name: "Quemchi")
Commune.find_or_create_by(region: r12, name: "Quinchao")
Commune.find_or_create_by(region: r12, name: "Osorno")
Commune.find_or_create_by(region: r12, name: "Puerto Octay")
Commune.find_or_create_by(region: r12, name: "Purranque")
Commune.find_or_create_by(region: r12, name: "Puyehue")
Commune.find_or_create_by(region: r12, name: "Río Negro")
Commune.find_or_create_by(region: r12, name: "San Juan de la Costa")
Commune.find_or_create_by(region: r12, name: "San Pablo")
Commune.find_or_create_by(region: r12, name: "Chaitén")
Commune.find_or_create_by(region: r12, name: "Futaleufú")
Commune.find_or_create_by(region: r12, name: "Hualaihué")
Commune.find_or_create_by(region: r12, name: "Palena")
Commune.find_or_create_by(region: r13, name: "Coihaique")
Commune.find_or_create_by(region: r13, name: "Lago Verde")
Commune.find_or_create_by(region: r13, name: "Aysén")
Commune.find_or_create_by(region: r13, name: "Cisnes")
Commune.find_or_create_by(region: r13, name: "Guaitecas")
Commune.find_or_create_by(region: r13, name: "Cochrane")
Commune.find_or_create_by(region: r13, name: "O'Higgins")
Commune.find_or_create_by(region: r13, name: "Tortel")
Commune.find_or_create_by(region: r13, name: "Chile Chico")
Commune.find_or_create_by(region: r13, name: "Río Ibáñez")
Commune.find_or_create_by(region: r14, name: "Punta Arenas")
Commune.find_or_create_by(region: r14, name: "Laguna Blanca")
Commune.find_or_create_by(region: r14, name: "Río Verde")
Commune.find_or_create_by(region: r14, name: "San Gregorio")
Commune.find_or_create_by(region: r14, name: "Cabo de Hornos")
Commune.find_or_create_by(region: r14, name: "Antártica")
Commune.find_or_create_by(region: r14, name: "Porvenir")
Commune.find_or_create_by(region: r14, name: "Primavera")
Commune.find_or_create_by(region: r14, name: "Timaukel")
Commune.find_or_create_by(region: r14, name: "Natales")
Commune.find_or_create_by(region: r14, name: "Torres del Paine")
